name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ cmake libgtest-dev

    - name: Build GoogleTest
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    - name: Configure Project
      run: cmake -S . -B build

    - name: Build Project
      run: cmake --build build

    - name: Run Tests
      run: ctest --output-on-failure --test-dir build
